/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    activityItems: ActivityItem;
    dailyBriefs: DailyBrief;
    dailyEngagements: DailyEngagement;
    events: Event;
    pointEvents: PointEvent;
    projects: Project;
    contributionRequests: ContributionRequest;
    threads: Thread;
    badges: Badge;
    profileBadges: ProfileBadge;
    modules: Module;
    spotlights: Spotlight;
    notifications: Notification;
    notificationPreferences: NotificationPreference;
    feedbackSubmissions: FeedbackSubmission;
    pageCopy: PageCopy;
    profiles: Profile;
    profileSkills: ProfileSkill;
    profileRoles: ProfileRole;
    inquiries: Inquiry;
    sponsorInquiries: SponsorInquiry;
    media: Media;
    categories: Category;
    users: User;
    comments: Comment;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    activityItems: ActivityItemsSelect<false> | ActivityItemsSelect<true>;
    dailyBriefs: DailyBriefsSelect<false> | DailyBriefsSelect<true>;
    dailyEngagements: DailyEngagementsSelect<false> | DailyEngagementsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    pointEvents: PointEventsSelect<false> | PointEventsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    contributionRequests: ContributionRequestsSelect<false> | ContributionRequestsSelect<true>;
    threads: ThreadsSelect<false> | ThreadsSelect<true>;
    badges: BadgesSelect<false> | BadgesSelect<true>;
    profileBadges: ProfileBadgesSelect<false> | ProfileBadgesSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    spotlights: SpotlightsSelect<false> | SpotlightsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    notificationPreferences: NotificationPreferencesSelect<false> | NotificationPreferencesSelect<true>;
    feedbackSubmissions: FeedbackSubmissionsSelect<false> | FeedbackSubmissionsSelect<true>;
    pageCopy: PageCopySelect<false> | PageCopySelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    profileSkills: ProfileSkillsSelect<false> | ProfileSkillsSelect<true>;
    profileRoles: ProfileRolesSelect<false> | ProfileRolesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    sponsorInquiries: SponsorInquiriesSelect<false> | SponsorInquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contentType?: ('article' | 'recap' | 'quote' | 'clip' | 'lesson' | 'announcement' | 'newsletter') | null;
  artifactKind?: ('article' | 'embed' | 'note') | null;
  sourceSession?: (number | null) | Event;
  parentThread?: (number | null) | Thread;
  relatedPosts?: (number | Post)[] | null;
  derivedFromPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  visibility: 'public' | 'authenticated' | 'member' | 'admin';
  wikiCandidate?: boolean | null;
  wikiCandidateTopics?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  sourceArtifactURL?: string | null;
  sourceArtifactID?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  summary?: string | null;
  sessionType: 'brownbag' | 'workshop' | 'all-hands' | 'demo' | 'pitch' | 'fireside';
  speaker?: (number | null) | Profile;
  /**
   * Optional hosts or facilitators for interview-style sessions.
   */
  hostProfiles?: (number | Profile)[] | null;
  /**
   * Optional guests or speakers. Prefer this for multi-speaker sessions.
   */
  speakerProfiles?: (number | Profile)[] | null;
  startsAt: string;
  endsAt?: string | null;
  locationLabel?: string | null;
  joinURL?: string | null;
  calendarURL?: string | null;
  discordEventURL?: string | null;
  discordScheduledEventID?: string | null;
  discordSyncStatus?: ('not_configured' | 'synced' | 'failed') | null;
  discordSyncError?: string | null;
  recordingURL?: string | null;
  transcriptArtifactURL?: string | null;
  summaryArtifactURL?: string | null;
  sourceArtifactURL?: string | null;
  /**
   * Source artifact ID for the primary transcript, summary, or source bundle.
   */
  sourceArtifactID?: string | null;
  sourceStatus?: ('scheduled' | 'recorded' | 'summarized' | 'processed' | 'archived') | null;
  /**
   * Stable key for lightweight recurring-session grouping, e.g. weekly-all-hands.
   */
  seriesKey?: string | null;
  /**
   * Display title for the recurring session group.
   */
  seriesTitle?: string | null;
  /**
   * Copied forward by agents/jobs when generating the next occurrence.
   */
  recurrenceCadence?: ('weekly' | 'biweekly' | 'monthly') | null;
  /**
   * Optional end date for recurrence generation.
   */
  recurrenceUntil?: string | null;
  previousOccurrence?: (number | null) | Event;
  nextOccurrence?: (number | null) | Event;
  roleFocus?: ('designer' | 'pm' | 'devops' | 'founder' | 'developer' | 'operations' | 'other') | null;
  practiceArea?: string | null;
  themes?:
    | {
        theme: string;
        id?: string | null;
      }[]
    | null;
  wikiCandidate?: boolean | null;
  wikiCandidateTopics?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  linkedSocialPosts?:
    | {
        platform: string;
        url: string;
        label?: string | null;
        publishedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Session-specific links such as notes, slides, docs, repos, or artifacts.
   */
  resources?:
    | {
        label: string;
        url: string;
        resourceType?: ('link' | 'notes' | 'slides' | 'doc' | 'repo' | 'design' | 'artifact' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  relatedProjects?: (number | Project)[] | null;
  relatedThreads?: (number | Thread)[] | null;
  relatedProfiles?: (number | Profile)[] | null;
  visibility: 'authenticated' | 'member' | 'public' | 'admin';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  /**
   * Blank users mark imported or legacy profiles as unclaimed.
   */
  user?: (number | null) | User;
  /**
   * Imported profiles can stay unclaimed until a matching account claims them.
   */
  claimStatus: 'unclaimed' | 'claimed';
  /**
   * Email from the legacy CRM used to match a new signup to this unclaimed profile.
   */
  claimEmail?: string | null;
  claimedAt?: string | null;
  /**
   * Optional legacy CRM identifier for import reconciliation.
   */
  sourceCRMID?: string | null;
  handle: string;
  displayName: string;
  bio: string;
  avatar?: (number | null) | Media;
  location?: string | null;
  walletAddress?: string | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    discord?: string | null;
    telegram?: string | null;
    farcaster?: string | null;
    /**
     * X handle without the @ symbol.
     */
    x?: string | null;
  };
  profileSkills: (number | ProfileSkill)[];
  profileRoles: (number | ProfileRole)[];
  status: 'active' | 'inactive';
  visibility: 'public' | 'authenticated' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'editor' | 'contributor' | 'member' | 'agent' | 'unverified')[] | null;
  /**
   * Set after the user verifies their account email from the portal.
   */
  emailVerifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profileSkills".
 */
export interface ProfileSkill {
  id: number;
  title: string;
  category?: string | null;
  description?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profileRoles".
 */
export interface ProfileRole {
  id: number;
  title: string;
  type?: string | null;
  group?: ('builder' | 'support') | null;
  description?: string | null;
  /**
   * Static public asset path used by member-facing profile flows.
   */
  iconPath?: string | null;
  icon?: (number | null) | Media;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  projectStatus?: ('active' | 'building' | 'archived' | 'exploratory' | 'exploring' | 'shipping') | null;
  visibility?: ('public' | 'authenticated' | 'member' | 'admin') | null;
  projectKind?:
    | (
        | 'community-project'
        | 'client-artifact'
        | 'internal-tool'
        | 'reference-repo'
        | 'rip'
        | 'program-project'
        | 'experiment'
        | 'template'
        | 'unknown'
      )
    | null;
  reviewStatus?:
    | (
        | 'unreviewed'
        | 'needs-review'
        | 'in-review'
        | 'needs-more-evidence'
        | 'ready-for-review'
        | 'ready-for-cms'
        | 'published'
      )
    | null;
  confidence?: ('low' | 'medium' | 'high') | null;
  historicalRelevance?: ('low' | 'medium' | 'high' | 'unknown') | null;
  claimedBy?: (number | null) | Profile;
  reviewedBy?: (number | null) | Profile;
  reviewedAt?: string | null;
  /**
   * Best-known project start date. For imported archives, this usually comes from repo creation or earliest source evidence.
   */
  startedAt?: string | null;
  /**
   * Best-known launch, delivery, or public release date.
   */
  launchedAt?: string | null;
  /**
   * Best-known completion, sunset, or handoff date.
   */
  completedAt?: string | null;
  currentState?:
    | {
        body: string;
        id?: string | null;
      }[]
    | null;
  lastActiveAt?: string | null;
  isFeatured?: boolean | null;
  featuredFrom?: string | null;
  featuredUntil?: string | null;
  /**
   * Higher values surface first when multiple projects are featured.
   */
  featuredPriority?: number | null;
  primaryCTA?: {
    label?: string | null;
    url?: string | null;
  };
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  /**
   * Profiles responsible for keeping this project surface accurate and managing related requests/activity.
   */
  stewards?: (number | Profile)[] | null;
  contributors?: (number | Profile)[] | null;
  /**
   * Use when this record is a repo, artifact, or duplicate that belongs under a primary project.
   */
  canonicalProject?: (number | null) | Project;
  /**
   * Related project records, component repos, companion artifacts, or follow-on work.
   */
  relatedProjects?: (number | Project)[] | null;
  /**
   * Why the current confidence level is justified.
   */
  confidenceRationale?: string | null;
  openQuestions?:
    | {
        question: string;
        status?: ('open' | 'answered' | 'not-applicable') | null;
        answer?: string | null;
        answeredBy?: (number | null) | Profile;
        answeredAt?: string | null;
        sourceURL?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Raw evidence used by importers and reviewers. Keep this separate from curated public links.
   */
  sourceEvidence?:
    | {
        sourceType: 'github' | 'discord' | 'valhalla' | 'rip' | 'charmverse' | 'website' | 'docs' | 'other';
        label: string;
        url?: string | null;
        sourceID?: string | null;
        confidence?: ('low' | 'medium' | 'high') | null;
        notes?: string | null;
        firstSeenAt?: string | null;
        lastSeenAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Candidate people extracted from commits, Discord, or docs before they are promoted to contributors.
   */
  peopleEvidence?:
    | {
        handle: string;
        role?: string | null;
        profile?: (number | null) | Profile;
        sourceType: 'github' | 'discord' | 'valhalla' | 'rip' | 'charmverse' | 'other';
        sourceURL?: string | null;
        confidence?: ('low' | 'medium' | 'high') | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  profileSkills?: (number | ProfileSkill)[] | null;
  activityItems?: (number | ActivityItem)[] | null;
  threads?: (number | Thread)[] | null;
  events?: (number | Event)[] | null;
  resources?:
    | {
        label: string;
        url: string;
        resourceType?: ('link' | 'repo' | 'design' | 'doc' | 'calendar' | 'discord') | null;
        id?: string | null;
      }[]
    | null;
  contributionActions?:
    | {
        title: string;
        description?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activityItems".
 */
export interface ActivityItem {
  id: number;
  title: string;
  body?: string | null;
  activityType: 'discussion' | 'decision' | 'project' | 'insight' | 'blocker' | 'event' | 'contribution';
  happenedAt: string;
  sourceLabel?: string | null;
  sourceURL?: string | null;
  relatedProject?: (number | null) | Project;
  relatedThread?: (number | null) | Thread;
  relatedEvent?: (number | null) | Event;
  relatedProfiles?: (number | Profile)[] | null;
  visibility: 'authenticated' | 'public' | 'admin';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "threads".
 */
export interface Thread {
  id: number;
  title: string;
  summary: string;
  threadStatus: 'active' | 'paused' | 'resolved' | 'archived';
  lastActiveAt?: string | null;
  participants?: (number | Profile)[] | null;
  relatedProjects?: (number | Project)[] | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  visibility: 'authenticated' | 'public' | 'admin';
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dailyBriefs".
 */
export interface DailyBrief {
  id: number;
  title: string;
  briefDate: string;
  /**
   * Daily briefs are for authenticated members. Weekly briefs can be public.
   */
  briefType: 'daily' | 'weekly';
  summary: string;
  /**
   * Short current-state label for the brief top strip, for example Active Now.
   */
  statusLabel?: string | null;
  /**
   * Short focus label for the brief top strip, for example Week 3 - Agent Workflows.
   */
  focusLabel?: string | null;
  sections: {
    heading: string;
    body: string;
    links?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Optional long-form narrative version of the brief.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional generated media for the brief, such as a Remotion scene export with audio.
   */
  mediaFile?: (number | null) | Media;
  /**
   * Optional externally hosted media URL, such as an S3 or CDN Remotion export.
   */
  externalMediaURL?: string | null;
  /**
   * Helps the frontend decide how to present the attached media.
   */
  mediaType?: ('video' | 'audio' | 'remotion-scene' | 'other') | null;
  nextEvent?: (number | null) | Event;
  activityItems?: (number | ActivityItem)[] | null;
  threads?: (number | Thread)[] | null;
  engagementActions?:
    | {
        label: string;
        description?: string | null;
        url: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  visibility: 'authenticated' | 'public' | 'admin';
  /**
   * Internal notes, source references, or generation context.
   */
  sourceNotes?: string | null;
  relatedPosts?: (number | Post)[] | null;
  relatedProjects?: (number | Project)[] | null;
  relatedProfiles?: (number | Profile)[] | null;
  authors?: (number | User)[] | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dailyEngagements".
 */
export interface DailyEngagement {
  id: number;
  user: number | User;
  profile?: (number | null) | Profile;
  /**
   * Normalized UTC day for once-per-day check-ins.
   */
  engagementDate: string;
  vibe: 'raiding' | 'ripping' | 'meeting' | 'learning' | 'vibing' | 'blocked' | 'resting';
  checkedIn: boolean;
  /**
   * Optional member note. Review status controls whether this can be displayed.
   */
  comment?: string | null;
  commentStatus: 'none' | 'pending_review' | 'approved' | 'hidden' | 'rejected';
  commentApprovedBy?: (number | null) | User;
  commentApprovedAt?: string | null;
  status: 'valid' | 'void';
  voidReason?: string | null;
  pointEvent?: (number | null) | PointEvent;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pointEvents".
 */
export interface PointEvent {
  id: number;
  recipient?: (number | null) | User;
  amount: number;
  reason: string;
  description?: string | null;
  source: 'admin' | 'system' | 'quest' | 'bounty' | 'import';
  status: 'valid' | 'reversed';
  issuedBy?: (number | null) | User;
  issuedAt: string;
  relatedProject?: (number | null) | Project;
  relatedPost?: (number | null) | Post;
  relatedDailyBrief?: (number | null) | DailyBrief;
  relatedDailyEngagement?: (number | null) | DailyEngagement;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contributionRequests".
 */
export interface ContributionRequest {
  id: number;
  title: string;
  summary: string;
  /**
   * Longer context, constraints, and response instructions for the ask.
   */
  body?: string | null;
  requestStatus: 'open' | 'in_discussion' | 'filled' | 'paused' | 'archived';
  requestType: 'good_first_contribution' | 'help_wanted' | 'review' | 'feedback' | 'collaborator' | 'resource';
  owner: number | Profile;
  /**
   * Primary project context for project-local display.
   */
  project?: (number | null) | Project;
  /**
   * Sessions or events this request came from or should display on.
   */
  relatedEvents?: (number | Event)[] | null;
  relatedThreads?: (number | Thread)[] | null;
  relatedPosts?: (number | Post)[] | null;
  /**
   * People who provide context, are referenced, or may be useful contacts.
   */
  relatedProfiles?: (number | Profile)[] | null;
  /**
   * Skills or roles that would help with this request.
   */
  profileSkills?: (number | ProfileSkill)[] | null;
  visibility: 'public' | 'authenticated' | 'member' | 'admin';
  /**
   * Where someone should respond, such as Discord, GitHub, or a form.
   */
  responseURL?: string | null;
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges".
 */
export interface Badge {
  id: number;
  title: string;
  description?: string | null;
  category: 'program' | 'contribution' | 'craft' | 'community' | 'achievement';
  artwork?: (number | null) | Media;
  fallbackIcon?: ('award' | 'spark' | 'shield' | 'star' | 'users') | null;
  /**
   * Optional CSS color used for member-facing display accents.
   */
  accentColor?: string | null;
  /**
   * Optional CSS color used for member-facing display backgrounds.
   */
  backgroundColor?: string | null;
  displayStyle: 'standard' | 'compact' | 'featured';
  isRetired?: boolean | null;
  sortOrder?: number | null;
  visibility: 'public' | 'member';
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profileBadges".
 */
export interface ProfileBadge {
  id: number;
  /**
   * Award this badge to one or more profiles.
   */
  profiles: (number | Profile)[];
  badge: number | Badge;
  awardedAt: string;
  awardedByUser?: (number | null) | User;
  source: 'admin' | 'agent' | 'program' | 'import' | 'system';
  relatedProject?: (number | null) | Project;
  relatedEvent?: (number | null) | Event;
  relatedPost?: (number | null) | Post;
  note?: string | null;
  featured?: boolean | null;
  visibility: 'public' | 'member' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  name: string;
  summary: string;
  status: 'idea' | 'prototype' | 'experimental' | 'active' | 'graduated' | 'archived';
  visibility: 'public' | 'authenticated' | 'member' | 'admin';
  /**
   * Enabled modules are listed on member-facing module surfaces.
   */
  enabled?: boolean | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  /**
   * Member-facing route when the module has a usable surface.
   */
  entryRoute?: string | null;
  /**
   * Optional admin route for managing module-owned records.
   */
  adminRoute?: string | null;
  /**
   * Spec, docs, or planning link for this module.
   */
  specURL?: string | null;
  /**
   * Optional implementation repository or PR link.
   */
  repositoryURL?: string | null;
  /**
   * Profiles stewarding or championing this module.
   */
  owners?: (number | Profile)[] | null;
  /**
   * Primary project that produced or maintains this module.
   */
  sourceProject?: (number | null) | Project;
  relatedProjects?: (number | Project)[] | null;
  relatedThreads?: (number | Thread)[] | null;
  relatedProfiles?: (number | Profile)[] | null;
  /**
   * Payload collection slugs owned by this module.
   */
  ownedCollections?:
    | {
        collectionSlug: string;
        id?: string | null;
      }[]
    | null;
  corePrimitiveRelationships?:
    | {
        primitive: 'brief' | 'project' | 'thread' | 'activityItem' | 'event' | 'profile' | 'post';
        id?: string | null;
      }[]
    | null;
  graduationCriteria?: string | null;
  riskNotes?: string | null;
  lastReviewedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spotlights".
 */
export interface Spotlight {
  id: number;
  title: string;
  summary?: string | null;
  kind: 'featured' | 'announcement';
  visibility: 'public' | 'authenticated' | 'member' | 'admin';
  startsAt?: string | null;
  /**
   * Announcements should usually expire after the relevant event or deadline.
   */
  expiresAt?: string | null;
  priority?: number | null;
  targetType: 'thread' | 'event' | 'project' | 'post' | 'profile' | 'external' | 'artifact';
  targetThread?: (number | null) | Thread;
  targetEvent?: (number | null) | Event;
  targetProject?: (number | null) | Project;
  targetPost?: (number | null) | Post;
  targetProfile?: (number | null) | Profile;
  externalURL?: string | null;
  artifactURL?: string | null;
  ctaLabel?: string | null;
  image?: (number | null) | Media;
  createdBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  title: string;
  body?: string | null;
  type:
    | 'event_published'
    | 'event_reminder'
    | 'brief_published'
    | 'activity_digest'
    | 'weekly_digest'
    | 'badge_awarded'
    | 'profile_claim'
    | 'system';
  status: 'unread' | 'read' | 'archived';
  priority: 'normal' | 'high';
  deliveryChannel: 'in_app' | 'email';
  emailStatus: 'none' | 'pending' | 'sent' | 'failed' | 'skipped';
  emailError?: string | null;
  readAt?: string | null;
  archivedAt?: string | null;
  emailedAt?: string | null;
  dedupeKey?: string | null;
  actionLabel?: string | null;
  actionURL?: string | null;
  relatedEvent?: (number | null) | Event;
  relatedBrief?: (number | null) | DailyBrief;
  relatedActivityItem?: (number | null) | ActivityItem;
  relatedProject?: (number | null) | Project;
  relatedThread?: (number | null) | Thread;
  relatedBadgeAward?: (number | null) | ProfileBadge;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationPreferences".
 */
export interface NotificationPreference {
  id: number;
  user: number | User;
  emailEnabled?: boolean | null;
  sessionAnnouncements: 'in_app' | 'email' | 'muted';
  sessionReminders: 'in_app' | 'email' | 'muted';
  briefs: 'in_app' | 'email' | 'muted';
  activityDigestFrequency: 'none' | 'daily' | 'weekly';
  weeklyDigest: 'in_app' | 'email' | 'muted';
  badgeAwards: 'in_app' | 'email' | 'muted';
  updatedAt: string;
  createdAt: string;
}
/**
 * Private user feedback, bug reports, and product ideas for admin triage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbackSubmissions".
 */
export interface FeedbackSubmission {
  id: number;
  type: 'bug' | 'feedback' | 'idea' | 'content_issue' | 'account_issue' | 'other';
  status: 'new' | 'triaged' | 'planned' | 'resolved' | 'closed' | 'spam';
  priority: 'low' | 'normal' | 'high' | 'urgent';
  title: string;
  message: string;
  email?: string | null;
  submittedBy?: (number | null) | User;
  submittedProfile?: (number | null) | Profile;
  pageURL?: string | null;
  userAgent?: string | null;
  viewport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Structured copy overrides for fixed Portal product-flow pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageCopy".
 */
export interface PageCopy {
  id: number;
  label: string;
  /**
   * Stable route key, for example join or inquire-client.
   */
  key: string;
  surface: 'join' | 'inquiry' | 'brief' | 'other';
  status: 'draft' | 'published';
  eyebrow?: string | null;
  headline?: string | null;
  intro?: string | null;
  secondaryIntro?: string | null;
  benefitsHeading?: string | null;
  benefits?:
    | {
        body: string;
        id?: string | null;
      }[]
    | null;
  funnelEyebrow?: string | null;
  funnelHeading?: string | null;
  funnelLinks?:
    | {
        label: string;
        description?: string | null;
        href: string;
        id?: string | null;
      }[]
    | null;
  contextHeading?: string | null;
  contextBody?: string | null;
  messageLabel?: string | null;
  submitLabel?: string | null;
  postSubmitEyebrow?: string | null;
  postSubmitHeading?: string | null;
  postSubmitBody?: string | null;
  createAccountLabel?: string | null;
  submitAnotherLabel?: string | null;
  backLinkLabel?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private intake records for onboarding, client, funding, and collaboration funnels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  type: 'client' | 'sponsor' | 'grant' | 'opportunity' | 'general';
  status: 'new' | 'reviewing' | 'contacted' | 'converted' | 'closed' | 'spam';
  accountLinkStatus: 'unlinked' | 'linked' | 'skipped';
  name: string;
  email: string;
  organization?: string | null;
  roleOrTitle?: string | null;
  message: string;
  budgetRange?: ('no-budget-yet' | 'under-5k' | '5k-15k' | '15k-50k' | '50k-plus' | 'unknown') | null;
  timeline?: ('this-week' | 'this-month' | 'this-quarter' | 'flexible') | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  sourceRoute?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  submitterUser?: (number | null) | User;
  submitterProfile?: (number | null) | Profile;
  relatedProject?: (number | null) | Project;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private intake records for sponsor, bounty, project, and funding opportunities.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsorInquiries".
 */
export interface SponsorInquiry {
  id: number;
  name: string;
  email: string;
  organization: string;
  sponsorType:
    | 'project-opportunity'
    | 'bounty-paid-work'
    | 'grant-funding'
    | 'mentorship-office-hours'
    | 'tooling-infrastructure'
    | 'other';
  /**
   * What the sponsor is bringing to the community.
   */
  opportunity: string;
  /**
   * Roles, skills, or kinds of collaborators requested.
   */
  contributorNeeds?: string | null;
  budgetRange?: ('no-budget-yet' | 'under-1k' | '1k-5k' | '5k-15k' | '15k-plus' | 'unknown') | null;
  timeline?: ('this-week' | 'this-month' | 'next-program-cycle' | 'flexible') | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  preferredNextStep?: ('talk-to-someone' | 'submit-for-review' | 'join-a-session') | null;
  /**
   * Whether this opportunity can be mentioned publicly after review.
   */
  canShowPublicly?: boolean | null;
  status: 'new' | 'reviewing' | 'accepted' | 'declined' | 'converted';
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Flat comments submitted by visitors on portal content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  content: string;
  author: {
    name: string;
    email: string;
  };
  parent:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'events';
        value: number | Event;
      }
    | {
        relationTo: 'projects';
        value: number | Project;
      }
    | {
        relationTo: 'contributionRequests';
        value: number | ContributionRequest;
      };
  /**
   * Visible comments can be hidden by unchecking this field.
   */
  isApproved?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'activityItems';
        value: number | ActivityItem;
      } | null)
    | ({
        relationTo: 'dailyBriefs';
        value: number | DailyBrief;
      } | null)
    | ({
        relationTo: 'dailyEngagements';
        value: number | DailyEngagement;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'pointEvents';
        value: number | PointEvent;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'contributionRequests';
        value: number | ContributionRequest;
      } | null)
    | ({
        relationTo: 'threads';
        value: number | Thread;
      } | null)
    | ({
        relationTo: 'badges';
        value: number | Badge;
      } | null)
    | ({
        relationTo: 'profileBadges';
        value: number | ProfileBadge;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'spotlights';
        value: number | Spotlight;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'notificationPreferences';
        value: number | NotificationPreference;
      } | null)
    | ({
        relationTo: 'feedbackSubmissions';
        value: number | FeedbackSubmission;
      } | null)
    | ({
        relationTo: 'pageCopy';
        value: number | PageCopy;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'profileSkills';
        value: number | ProfileSkill;
      } | null)
    | ({
        relationTo: 'profileRoles';
        value: number | ProfileRole;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'sponsorInquiries';
        value: number | SponsorInquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  contentType?: T;
  artifactKind?: T;
  sourceSession?: T;
  parentThread?: T;
  relatedPosts?: T;
  derivedFromPosts?: T;
  categories?: T;
  visibility?: T;
  wikiCandidate?: T;
  wikiCandidateTopics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  sourceArtifactURL?: T;
  sourceArtifactID?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activityItems_select".
 */
export interface ActivityItemsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  activityType?: T;
  happenedAt?: T;
  sourceLabel?: T;
  sourceURL?: T;
  relatedProject?: T;
  relatedThread?: T;
  relatedEvent?: T;
  relatedProfiles?: T;
  visibility?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dailyBriefs_select".
 */
export interface DailyBriefsSelect<T extends boolean = true> {
  title?: T;
  briefDate?: T;
  briefType?: T;
  summary?: T;
  statusLabel?: T;
  focusLabel?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  content?: T;
  mediaFile?: T;
  externalMediaURL?: T;
  mediaType?: T;
  nextEvent?: T;
  activityItems?: T;
  threads?: T;
  engagementActions?:
    | T
    | {
        label?: T;
        description?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  visibility?: T;
  sourceNotes?: T;
  relatedPosts?: T;
  relatedProjects?: T;
  relatedProfiles?: T;
  authors?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dailyEngagements_select".
 */
export interface DailyEngagementsSelect<T extends boolean = true> {
  user?: T;
  profile?: T;
  engagementDate?: T;
  vibe?: T;
  checkedIn?: T;
  comment?: T;
  commentStatus?: T;
  commentApprovedBy?: T;
  commentApprovedAt?: T;
  status?: T;
  voidReason?: T;
  pointEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  sessionType?: T;
  speaker?: T;
  hostProfiles?: T;
  speakerProfiles?: T;
  startsAt?: T;
  endsAt?: T;
  locationLabel?: T;
  joinURL?: T;
  calendarURL?: T;
  discordEventURL?: T;
  discordScheduledEventID?: T;
  discordSyncStatus?: T;
  discordSyncError?: T;
  recordingURL?: T;
  transcriptArtifactURL?: T;
  summaryArtifactURL?: T;
  sourceArtifactURL?: T;
  sourceArtifactID?: T;
  sourceStatus?: T;
  seriesKey?: T;
  seriesTitle?: T;
  recurrenceCadence?: T;
  recurrenceUntil?: T;
  previousOccurrence?: T;
  nextOccurrence?: T;
  roleFocus?: T;
  practiceArea?: T;
  themes?:
    | T
    | {
        theme?: T;
        id?: T;
      };
  wikiCandidate?: T;
  wikiCandidateTopics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  linkedSocialPosts?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        publishedAt?: T;
        id?: T;
      };
  resources?:
    | T
    | {
        label?: T;
        url?: T;
        resourceType?: T;
        id?: T;
      };
  relatedProjects?: T;
  relatedThreads?: T;
  relatedProfiles?: T;
  visibility?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pointEvents_select".
 */
export interface PointEventsSelect<T extends boolean = true> {
  recipient?: T;
  amount?: T;
  reason?: T;
  description?: T;
  source?: T;
  status?: T;
  issuedBy?: T;
  issuedAt?: T;
  relatedProject?: T;
  relatedPost?: T;
  relatedDailyBrief?: T;
  relatedDailyEngagement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  description?: T;
  projectStatus?: T;
  visibility?: T;
  projectKind?: T;
  reviewStatus?: T;
  confidence?: T;
  historicalRelevance?: T;
  claimedBy?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  startedAt?: T;
  launchedAt?: T;
  completedAt?: T;
  currentState?:
    | T
    | {
        body?: T;
        id?: T;
      };
  lastActiveAt?: T;
  isFeatured?: T;
  featuredFrom?: T;
  featuredUntil?: T;
  featuredPriority?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        url?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  coverImage?: T;
  stewards?: T;
  contributors?: T;
  canonicalProject?: T;
  relatedProjects?: T;
  confidenceRationale?: T;
  openQuestions?:
    | T
    | {
        question?: T;
        status?: T;
        answer?: T;
        answeredBy?: T;
        answeredAt?: T;
        sourceURL?: T;
        id?: T;
      };
  sourceEvidence?:
    | T
    | {
        sourceType?: T;
        label?: T;
        url?: T;
        sourceID?: T;
        confidence?: T;
        notes?: T;
        firstSeenAt?: T;
        lastSeenAt?: T;
        id?: T;
      };
  peopleEvidence?:
    | T
    | {
        handle?: T;
        role?: T;
        profile?: T;
        sourceType?: T;
        sourceURL?: T;
        confidence?: T;
        notes?: T;
        id?: T;
      };
  profileSkills?: T;
  activityItems?: T;
  threads?: T;
  events?: T;
  resources?:
    | T
    | {
        label?: T;
        url?: T;
        resourceType?: T;
        id?: T;
      };
  contributionActions?:
    | T
    | {
        title?: T;
        description?: T;
        url?: T;
        id?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contributionRequests_select".
 */
export interface ContributionRequestsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  body?: T;
  requestStatus?: T;
  requestType?: T;
  owner?: T;
  project?: T;
  relatedEvents?: T;
  relatedThreads?: T;
  relatedPosts?: T;
  relatedProfiles?: T;
  profileSkills?: T;
  visibility?: T;
  responseURL?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "threads_select".
 */
export interface ThreadsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  threadStatus?: T;
  lastActiveAt?: T;
  participants?: T;
  relatedProjects?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  visibility?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges_select".
 */
export interface BadgesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  artwork?: T;
  fallbackIcon?: T;
  accentColor?: T;
  backgroundColor?: T;
  displayStyle?: T;
  isRetired?: T;
  sortOrder?: T;
  visibility?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profileBadges_select".
 */
export interface ProfileBadgesSelect<T extends boolean = true> {
  profiles?: T;
  badge?: T;
  awardedAt?: T;
  awardedByUser?: T;
  source?: T;
  relatedProject?: T;
  relatedEvent?: T;
  relatedPost?: T;
  note?: T;
  featured?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  name?: T;
  summary?: T;
  status?: T;
  visibility?: T;
  enabled?: T;
  featured?: T;
  sortOrder?: T;
  entryRoute?: T;
  adminRoute?: T;
  specURL?: T;
  repositoryURL?: T;
  owners?: T;
  sourceProject?: T;
  relatedProjects?: T;
  relatedThreads?: T;
  relatedProfiles?: T;
  ownedCollections?:
    | T
    | {
        collectionSlug?: T;
        id?: T;
      };
  corePrimitiveRelationships?:
    | T
    | {
        primitive?: T;
        id?: T;
      };
  graduationCriteria?: T;
  riskNotes?: T;
  lastReviewedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spotlights_select".
 */
export interface SpotlightsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  kind?: T;
  visibility?: T;
  startsAt?: T;
  expiresAt?: T;
  priority?: T;
  targetType?: T;
  targetThread?: T;
  targetEvent?: T;
  targetProject?: T;
  targetPost?: T;
  targetProfile?: T;
  externalURL?: T;
  artifactURL?: T;
  ctaLabel?: T;
  image?: T;
  createdBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  title?: T;
  body?: T;
  type?: T;
  status?: T;
  priority?: T;
  deliveryChannel?: T;
  emailStatus?: T;
  emailError?: T;
  readAt?: T;
  archivedAt?: T;
  emailedAt?: T;
  dedupeKey?: T;
  actionLabel?: T;
  actionURL?: T;
  relatedEvent?: T;
  relatedBrief?: T;
  relatedActivityItem?: T;
  relatedProject?: T;
  relatedThread?: T;
  relatedBadgeAward?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationPreferences_select".
 */
export interface NotificationPreferencesSelect<T extends boolean = true> {
  user?: T;
  emailEnabled?: T;
  sessionAnnouncements?: T;
  sessionReminders?: T;
  briefs?: T;
  activityDigestFrequency?: T;
  weeklyDigest?: T;
  badgeAwards?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbackSubmissions_select".
 */
export interface FeedbackSubmissionsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  priority?: T;
  title?: T;
  message?: T;
  email?: T;
  submittedBy?: T;
  submittedProfile?: T;
  pageURL?: T;
  userAgent?: T;
  viewport?: T;
  metadata?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageCopy_select".
 */
export interface PageCopySelect<T extends boolean = true> {
  label?: T;
  key?: T;
  surface?: T;
  status?: T;
  eyebrow?: T;
  headline?: T;
  intro?: T;
  secondaryIntro?: T;
  benefitsHeading?: T;
  benefits?:
    | T
    | {
        body?: T;
        id?: T;
      };
  funnelEyebrow?: T;
  funnelHeading?: T;
  funnelLinks?:
    | T
    | {
        label?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  contextHeading?: T;
  contextBody?: T;
  messageLabel?: T;
  submitLabel?: T;
  postSubmitEyebrow?: T;
  postSubmitHeading?: T;
  postSubmitBody?: T;
  createAccountLabel?: T;
  submitAnotherLabel?: T;
  backLinkLabel?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  user?: T;
  claimStatus?: T;
  claimEmail?: T;
  claimedAt?: T;
  sourceCRMID?: T;
  handle?: T;
  displayName?: T;
  bio?: T;
  avatar?: T;
  location?: T;
  walletAddress?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        discord?: T;
        telegram?: T;
        farcaster?: T;
        x?: T;
      };
  profileSkills?: T;
  profileRoles?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profileSkills_select".
 */
export interface ProfileSkillsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  description?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profileRoles_select".
 */
export interface ProfileRolesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  group?: T;
  description?: T;
  iconPath?: T;
  icon?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  accountLinkStatus?: T;
  name?: T;
  email?: T;
  organization?: T;
  roleOrTitle?: T;
  message?: T;
  budgetRange?: T;
  timeline?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  sourceRoute?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  submitterUser?: T;
  submitterProfile?: T;
  relatedProject?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsorInquiries_select".
 */
export interface SponsorInquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  organization?: T;
  sponsorType?: T;
  opportunity?: T;
  contributorNeeds?: T;
  budgetRange?: T;
  timeline?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  preferredNextStep?: T;
  canShowPublicly?: T;
  status?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  emailVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  content?: T;
  author?:
    | T
    | {
        name?: T;
        email?: T;
      };
  parent?: T;
  isApproved?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        id?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}